config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'

    delete 'auth/logout', to: 'auth#logout'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth

    resources :bulletins, only: %i[index show new edit create update] do
      member do
        patch :to_moderate
        patch :archive
      end
    end

    resource :profile, only: :show

    namespace :admin do
      resources :categories, only: %i[index new edit create update destroy]
      resources :bulletins, only: :index do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
      end
      root 'home#index'
    end
  end
end

app/views/layouts/shared/_flash.html.slim
- flash.each do |type, message|
    | <div class="container d-flex justify-content-between alert alert-
    = type
    | ">
    = message
    button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'
    | </div>

app/views/layouts/shared/_footer.html.slim
footer.bg-dark.text-light.mt-auto
  .container-xl
    .row.py-2
      = t('titles.hexlet')

app/views/layouts/shared/_nav.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      = link_to t('titles.app'), root_path, class: 'navbar-brand me-md-4'
      - if signed_in?
        .collapse.navbar-collapse
          ul.nav.nav-pills.flex-grow-1.navbar-nav.me-auto
            li.nav-item.me-2
              = link_to t('links.main'), root_path, class: 'nav-link text-dark'
            li.nav-item.me-2
              = link_to t('links.my_bulletins'), profile_path, class: 'nav-link text-dark'
            li.nav-item.me-2
              = link_to t('links.add'), new_bulletin_path, class: 'nav-link text-dark'
    ul.nav.nav-pills
      - if signed_in?
        li.nav-item.me-2
          = link_to t('links.admin'), admin_root_path, class: 'nav-link text-dark' if current_user.admin?
        li.nav-item.me-2
          = button_to t('links.log_out'), auth_logout_path, method: :delete, class: 'nav-link text-dark'
      - else
        li.nav-item.me-2
          = button_to auth_request_path(:github), data: { turbo: false }, class: 'nav-link text-dark' do
            span.bi.bi-github.me-2
            = t('links.log_in')