config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'

    delete 'auth/logout', to: 'auth#logout'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth

    resources :bulletins, only: %i[index show new edit create update] do
      member do
        patch :to_moderate
        patch :archive
      end
    end

    resource :profile, only: :show

    namespace :admin do
      resources :categories, only: %i[index new edit create update destroy]
      resources :bulletins, only: :index do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
      end
      root 'home#index'
    end
  end
end

app/controllers/web/admin/home_controller.rb
# frozen_string_literal: true

class Web::Admin::HomeController < Web::Admin::ApplicationController
  def index
    @bulletins = Bulletin.under_moderation
    params[:active_link] = 'moderate'
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/web/admin/home/index.html.slim
.container
  .row
    .col-md-3
      = render partial: 'web/admin/shared/nav'
    .col-md-9
      h1.h2.mb-4 = t('titles.on_moderate')
      .row.mt-2
        table.table.table-borderless
          thead
            tr
              th = t('activerecord.attributes.bulletin.title')
              th = t('activerecord.attributes.bulletin.created_at')
              th = t('activerecord.attributes.bulletin.actions')
          tbody
            - @bulletins.each do |bulletin|
              tr
                td = bulletin.title
                td = time_ago_in_words(bulletin.created_at)
                td
                  = link_to t('links.publish'), publish_admin_bulletin_path(bulletin),
                                                data: { turbo_method: :patch },
                                                class: 'me-2'
                  = link_to t('links.reject'), reject_admin_bulletin_path(bulletin),
                                                data: { turbo_method: :patch },
                                                class: 'me-2'
                  = link_to t('links.archive'), archive_admin_bulletin_path(bulletin),
                                            data: { turbo_method: :patch, turbo_confirm: t('confirmations.archive') },
                                            class: 'link-danger me-2'