config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'

    delete 'auth/logout', to: 'auth#logout'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth

    resources :bulletins, only: %i[index show new edit create update] do
      member do
        patch :to_moderate
        patch :archive
      end
    end

    resource :profile, only: :show

    namespace :admin do
      resources :categories, only: %i[index new edit create update destroy]
      resources :bulletins, only: :index do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
      end
      root 'home#index'
    end
  end
end

app/controllers/web/profile_controller.rb
# frozen_string_literal: true

class Web::ProfileController < Web::ApplicationController
  before_action :authenticate_user!

  def index
    @query = current_user.bulletins.ransack(params[:query])

    @bulletins = @query.result.page(params[:page]).per(5)
  end
end

app/controllers/web/profiles_controller.rb
# frozen_string_literal: true

class Web::ProfilesController < Web::ApplicationController
  before_action :authenticate_user!

  def show
    @query = current_user.bulletins.ransack(params[:query])

    @bulletins = @query.result.page(params[:page]).per(5)
  end
end

app/views/web/profiles/show.html.slim
.mt-4.mb-5.pb-5
  .container
    .p-4.align-items-center.border.shadow.bg-white.rounded-3
      .row
        .p-3.p-lg-5.pt-lg-0
          .mb-4
            h2 = t('titles.my_bulletins')
            hr
          = link_to t('links.add_bulletin'), new_bulletin_path
          = render 'web/shared/search_form', query: @query, url: profile_path
          .row.mt-2
            table.table.table-borderless
              thead
                tr
                  th = t('activerecord.attributes.bulletin.title')
                  th = t('activerecord.attributes.bulletin.state')
                  th = t('activerecord.attributes.bulletin.created_at')
                  th = t('activerecord.attributes.bulletin.actions')
              tbody
                - @bulletins.each do |bulletin|
                  tr
                    td = bulletin.title
                    td = bulletin.aasm.human_state
                    td = time_ago_in_words(bulletin.created_at)
                    td
                      = link_to t('links.show'), bulletin_path(bulletin), class: 'me-2'
                      = link_to t('links.edit'), edit_bulletin_path(bulletin), class: 'me-2'
                      - if bulletin.may_to_moderate?
                        = link_to t('links.to_moderate'), to_moderate_bulletin_path(bulletin),
                                                          data: { turbo_method: :patch },
                                                          class: 'me-2'

                      - if bulletin.may_archive?
                        = link_to t('links.archive'), archive_bulletin_path(bulletin),
                                              data: { turbo_method: :patch, turbo_confirm: t('confirmations.archive') },
                                              class: 'link-danger me-2'
      = paginate @bulletins, pagination_class: 'pagination flex-wrap justify-content-end', nav_class: 'pt-3'