config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'

    delete 'auth/logout', to: 'auth#logout'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth

    resources :bulletins, only: %i[index show new edit create update] do
      member do
        patch :to_moderate
        patch :archive
      end
    end

    resource :profile, only: :show

    namespace :admin do
      resources :categories, only: %i[index new edit create update destroy]
      resources :bulletins, only: :index do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
      end
      root 'home#index'
    end
  end
end

app/models/bulletin.rb
# frozen_string_literal: true

class Bulletin < ApplicationRecord
  include AASM

  belongs_to :user
  belongs_to :category

  has_one_attached :image

  aasm column: 'state' do
    state :draft, initial: true
    state :under_moderation, :published, :rejected, :archived

    event :to_moderate do
      transitions from: :draft, to: :under_moderation
    end

    event :publish do
      transitions from: :under_moderation, to: :published
    end

    event :reject do
      transitions from: :under_moderation, to: :rejected
    end

    event :archive do
      transitions from: %i[draft under_moderation published rejected], to: :archived
    end
  end

  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 1000 }

  validates :image, attached: true,
                    content_type: ['image/png', 'image/jpg', 'image/jpeg'],
                    size: { less_than: 5.megabytes,
                            message: I18n.t('image_size_message') }

  scope :order_by_desc, -> { order(created_at: :desc) }

  def self.ransackable_attributes(_auth_object = nil)
    %w[state title category_id]
  end
end

app/controllers/web/admin/bulletins_controller.rb
# frozen_string_literal: true

class Web::Admin::BulletinsController < Web::Admin::ApplicationController
  def index
    @query = Bulletin.order_by_desc.ransack(params[:query])
    @bulletins = @query.result.page(params[:page]).per(5)

    params[:active_link] = 'bulletins'
  end

  def publish
    @bulletin = set_bulletin

    if @bulletin.may_publish?
      @bulletin.publish!

      flash[:primary] = t('aasm.success.publish')
      redirect_to admin_root_path
    else
      flash[:danger] = t('aasm.failure.publish')
      redirect_back(fallback_location: admin_root_path)
    end
  end

  def reject
    @bulletin = set_bulletin

    if @bulletin.may_reject?
      @bulletin.reject!

      flash[:primary] = t('aasm.success.reject')
      redirect_to admin_root_path
    else
      flash[:danger] = t('aasm.failure.reject')
      redirect_back(fallback_location: admin_root_path)
    end
  end

  def archive
    @bulletin = set_bulletin

    if @bulletin.may_archive?
      @bulletin.archive!

      flash[:primary] = t('aasm.success.archive')
      redirect_to admin_root_path
    else
      flash[:danger] = t('aasm.failure.archive')
      redirect_back(fallback_location: admin_root_path)
    end
  end

  private

  def set_bulletin
    @bulletin = Bulletin.find params[:id]
  end
end

app/controllers/web/bulletins_controller.rb
# frozen_string_literal: true

class Web::BulletinsController < Web::ApplicationController
  before_action :authenticate_user!, only: %i[new edit create update to_moderate archive]

  def index
    @query = Bulletin.published.order_by_desc.ransack(params[:query])

    @bulletins = @query.result.page(params[:page]).per(10)
  end

  def show
    @bulletin = set_bulletin

    authorize @bulletin
  end

  def new
    @bulletin = current_user.bulletins.build
  end

  def edit
    @bulletin = set_bulletin

    authorize @bulletin
  end

  def create
    @bulletin = current_user.bulletins.build(bulletin_params)

    if @bulletin.save
      flash[:primary] = t('bulletins.create.success')
      redirect_to @bulletin
    else
      flash[:danger] = @bulletin.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @bulletin = set_bulletin

    authorize @bulletin

    if @bulletin.update(bulletin_params)
      flash[:primary] = t('bulletins.update.success')
      redirect_to profile_path
    else
      flash[:danger] = @bulletin.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end

  def to_moderate
    @bulletin = set_bulletin

    authorize @bulletin

    if @bulletin.may_to_moderate?
      @bulletin.to_moderate!

      flash[:primary] = t('aasm.success.to_moderate')
      redirect_to profile_path
    else
      flash[:danger] = t('aasm.failure.to_moderate')
      redirect_back(fallback_location: profile_path)
    end
  end

  def archive
    @bulletin = set_bulletin

    authorize @bulletin

    if @bulletin.may_archive?
      @bulletin.archive!

      flash[:primary] = t('aasm.success.archive')
      redirect_to profile_path
    else
      flash[:danger] = t('aasm.failure.archive')
      redirect_back(fallback_location: profile_path)
    end
  end

  private

  def set_bulletin
    @bulletin = Bulletin.find params[:id]
  end

  def bulletin_params
    params.require(:bulletin).permit(:title, :description, :category_id, :image)
  end
end

app/views/web/admin/bulletins/index.html.slim
.container
  .row
    .col-md-3
      = render partial: 'web/admin/shared/nav'
    .col-md-9
      h1.h2.mb-4 = t('titles.all_bulletins')
      .row.mt-2
        = render 'web/shared/search_form', query: @query, url: admin_bulletins_path
        table.table.table-borderless
          thead
            tr
              th = t('activerecord.attributes.bulletin.title')
              th = t('activerecord.attributes.bulletin.state')
              th = t('activerecord.attributes.bulletin.created_at')
              th = t('activerecord.attributes.bulletin.actions')
          tbody
            - @bulletins.each do |bulletin|
              tr
                td
                  = link_to bulletin.title, bulletin_path(bulletin)
                td = bulletin.aasm.human_state
                td = time_ago_in_words(bulletin.created_at)
                td
                  = link_to t('links.show'), bulletin_path(bulletin), class: 'me-2'
                  = link_to t('links.archive'), archive_admin_bulletin_path(bulletin),
                                            data: { turbo_method: :patch, turbo_confirm: t('confirmations.archive') },
                                            class: 'link-danger me-2'
        = paginate @bulletins, pagination_class: 'pagination flex-wrap justify-content-end', nav_class: 'pt-3'